# Generated by Django 3.0.4 on 2020-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20200318_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='fileName',
            field=models.CharField(default='text', max_length=1000),
            preserve_default=False,
        ),
    ]
