# Generated by Django 3.0.4 on 2020-03-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_cloudfile_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='fileName',
        ),
    ]
