# Generated by Django 3.0.4 on 2020-03-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_remove_cloudfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='fileName',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
